# Generated by Django 4.1.3 on 2023-01-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='apartment_number',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='myuser',
            name='building_number',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='street',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='zip_code',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
