# Generated by Django 4.1.3 on 2023-01-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_apartment_number_myuser_building_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='apartment_number',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='building_number',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='street',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='zip_code',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
    ]
