# Generated by Django 4.1.5 on 2023-04-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='if_paid',
            new_name='is_paid',
        ),
        migrations.AlterField(
            model_name='order',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=100),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='postage',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
