# Generated by Django 4.1.7 on 2023-03-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='shipping_method',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ShippingMethod',
        ),
    ]
