# Generated by Django 4.1.7 on 2023-03-31 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productindex_is_available'),
        ('orders', '0003_alter_orderitem_product_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productindex'),
        ),
    ]
