# Generated by Django 4.1.5 on 2023-01-11 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cd',
            old_name='author',
            new_name='band',
        ),
    ]
