# Generated by Django 4.1.7 on 2023-03-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productindex',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
