# Generated by Django 4.1.5 on 2023-02-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='apartment_number',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
