# Generated by Django 4.1.5 on 2023-02-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='debt',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
