# Generated by Django 4.1.5 on 2023-01-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(choices=[('Horror', 'Horror'), ('Comedy', 'Comedy')], default=None, max_length=30),
        ),
    ]
