# Generated by Django 4.1.5 on 2023-01-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='genre',
        ),
    ]
